services:
  - type: web
    name: snake-perfekt
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
    healthCheckPath: /health
    autoDeploy: true
